# Generated by Django 2.1.7 on 2019-02-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, default=None, max_length=255)),
                ('contact_number', models.TextField(blank=True, default=None, max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('left_leg_len', models.DecimalField(blank=True, decimal_places=5, default=False, max_digits=5)),
                ('right_leg_len', models.DecimalField(blank=True, decimal_places=5, default=False, max_digits=5)),
                ('weight', models.DecimalField(blank=True, decimal_places=5, default=False, max_digits=5)),
            ],
        ),
    ]
