# Generated by Django 2.1.7 on 2019-04-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190401_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatamodel',
            name='pref_color',
        ),
        migrations.RemoveField(
            model_name='userdatamodel',
            name='pref_width',
        ),
    ]
